### ISSUE TITLE
Try to import native types first

### ISSUE THREAD

**Issue by rchl** [packagecontrol/typing#1]
Could this dependency import types the way LSP does:

https://github.com/sublimelsp/LSP/blob/st4000-exploration/plugin/core/typing.py

?

That is, import native `typing` if the version is right and only fallback to "own" otherwise?

The problem with the way it's done currently is that it's not playing well with LSP since running the LSP runtime in 3.8 environment, the LSP will "see" both those custom types and native types and will mark the types as incompatible.

@rwols

**Comment by FichteFoll** [comment]
Am I right to assume that this is a result of how LSP-pyright appends dependencies' paths to pyright's lookup paths and does not have anything to do with ST itself? Because I don't see why this module would even be importable from the Python 3.8 runtime if PC doesn't support it.

**Comment by rchl** [comment]
Even though packages run in the 3.3 python, they are typically being developed in a LSP context that uses 3.7 (or later) environment since that's what the user has installed and because those versions have proper types support which is important for LSP.

But maybe I have assumed too much and I should rather focus on specific issues I'm seeing which are maybe more related to `sublime_lib` itself.

For example in here:

![Screenshot 2021-05-11 at 09 18 00](https://user-images.githubusercontent.com/153197/117774916-40351500-b23a-11eb-9b78-e8e973211aa5.png)

the `Optional` is a very empty stub so it doesn't support generic arguments. It uses `Optional` from `st3/sublime_lib/_compat/typing_stubs.py`.

(We could probably move this to `sublime_lib` and only come back here once the the specific issues are sorted out).

**Comment by FichteFoll** [comment]
In my eyes, this is a tooling issue and not something that should or even needs to be solved in the `typing` backport, if it's even possible.

As for `sublime_lib`, have you updated to the latest release yet? There was a problem with the 1.5.1 hotfix, which is why 1.5.2 was released a few days ago.

**Comment by rchl** [comment]
Yeah, I'm on latest `sublime_lib`.

I see now that `sublime_lib` has this logic:
https://github.com/SublimeText/sublime_lib/blob/master/st3/sublime_lib/_compat/typing.py
but Pyright doesn't do what one would expect when using `try/except`. It would work correctly when done this way:
https://github.com/sublimelsp/LSP/blob/82120a8b67124c22ea01d2723c6a63a3150f5936/plugin/core/typing.py#L3-L3

But of course that is not really compatible with a package that is supposed provide stubs for versions lower than 3.8...

**Comment by rwols** [comment]
We solve the pyright tooling problem once sublime_lib uses the sys.version_info trick right? I don’t really understand your last sentence @rchl.

**Comment by rchl** [comment]
When pyright is in a `dev_environment: sublime_text` mode then what will happen if the `typing` dependency is installed in ST? Even if we do something like:
```
if sys.version_info >= (3, 8, 0):
    from typing import *  # noqa: F401, F403
else:
    try:
        from typing import *  # noqa: F401, F403
    except ImportError:
        from .typing_stubs import *  # type: ignore # noqa: F401, F403
```

it will probably always try to import the ST dependency instead of the native `typing`? In which case it would not solve the problem.

**Comment by rwols** [comment]
Ah I see. The second line will still import everything from this module since it's earlier in the python search path. So yeah, I think this dependency should use the `sys.version_info` check as well.

**Comment by FichteFoll** [comment]
Does pyright have a target language option? If using pyright with `dev_environment: sublime_text` yields problems because of a non-standard environment, couldn't you just not make the PC `typing` ~~dependency~~ library discoverable for pyright (by e.g. blacklisting it)?

**Comment by rchl** [comment]
Hmm, actually dependencies are not added already. Not sure what my issue is anymore...

**Comment by rchl** [comment]
Created https://github.com/SublimeText/sublime_lib/issues/171 for the actual issue I was thinking about.
